name: Execute Curl POST Request

on:
    push:
      branches:
        - master
    workflow_dispatch:  # Enable manual triggering

jobs:
  curl-job:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Execute Curl POST Request
      env:
        EMAIL: ${{ secrets.EMAIL }}
        PASSWORD: ${{ secrets.PASSWORD }}
        API_URL: ${{ secrets.API_URL }}
        API_KEY: ${{ secrets.API_KEY }}
      run: |
        curl --request POST \
        --url $API_URL \
        --header "Accept: application/json" \
        --header "Content-Type: application/json" \
        --data "$(jq -n --arg email "$EMAIL" --arg password "$PASSWORD" '{email: $email, password: $password}')"


    - name: clone frontend-v2
      uses: actions/checkout@v2
      with:
        repository: 'HeRAMS-WHO/herams-v2-frontend'
        path: 'herams-v2-frontend'
        ssh-key: ${{ secrets.V2_I18N_PRIVATE_KEY }}

    - name: test frontend-v2
      run: ls -la && cd herams-v2-frontend

    # - name: Checkout frontend
    #   run: |
    #     git clone git@github.com:HeRAMS-WHO/herams-v2-frontend.git
    #     cd herams-v2-backend