name: Execute Curl POST Request

on: [push]

jobs:
  curl-job:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Execute Curl POST Request
      run: |
        API_URL="http://heramsv2-backend.test/api/"
        API_KEY="179|KPPgEMqoQTOL5lLHcns5VPfIRDcZRUWHVBvEpNdZ9ec9604a"
        curl --request POST \
          --url https://dev-v2.herams-stg.org/api/authentication/login \
          --header 'Accept: application/json' \
          --header 'Content-Type: application/json' \
          --data '{
            "email":"casisc@who.int",
            "password":"g_UGNJY6Z+/Ft8z%nm'k=d"
          }'
